using System;
using System.Collections.Generic;

namespace UltrawideToys;

internal static class Localization
{
	private static readonly Dictionary<string, string> Fr = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
	{
		["Zones"] = "Zones",
		["ZonesDescription"] = "Créez des espaces de travail personnalisés pour chaque écran.",
		["Behavior"] = "Comportement",
		["Startup"] = "Démarrage",
		["Appearance"] = "Apparence et langue",
		["Compatibility"] = "Compatibilité",
		["About"] = "À propos",
		["Edit"] = "Modifier",
		["Apply"] = "Appliquer",
		["Cancel"] = "Annuler",
		["Reset"] = "Réinitialiser",
		["Enabled"] = "Ultrawide Monitor est actif",
		["Monitor"] = "Écran",
		["Primary"] = "Principal",
		["Preset"] = "Disposition",
		["AddPreset"] = "Enregistrer comme preset",
		["Maximize"] = "Maximiser les fenêtres dans une zone",
		["ShiftBypass"] = "Maj maximise sur tout l’écran",
		["Snap"] = "Aimantation des bords",
		["SnapDistance"] = "Distance d’aimantation",
		["StartWithWindows"] = "Lancer avec Windows",
		["StartMinimized"] = "Démarrer réduit dans la zone de notification",
		["AdminAgent"] = "Agent administrateur",
		["Language"] = "Langue",
		["Theme"] = "Thème",
		["System"] = "Système",
		["Light"] = "Clair",
		["Dark"] = "Sombre",
		["Add"] = "Ajouter",
		["Remove"] = "Supprimer",
		["Process"] = "Processus",
		["AboutText"] = "Ultrawide Monitor est un gestionnaire de zones pour Windows 11. Aucun compte, aucune télémétrie.",
		["GithubCredit"] = "Projet, code source et versions : GitHub / ImRedTV",
		["UpdateTitle"] = "Mise à jour disponible",
		["UpdateMessage"] = "La version {0} d’Ultrawide Monitor est disponible. Voulez-vous ouvrir la dernière release GitHub ?",
		["DoubleClick"] = "Double-cliquez sur l’icône de notification pour modifier les zones.",
		["NoMonitors"] = "Aucun écran détecté.",
		["Selected"] = "Sélectionné",
		["TrayEnabled"] = "Ultrawide Monitor est actif",
		["TrayEdit"] = "Modifier les zones…",
		["TraySettings"] = "Paramètres…",
		["TrayStartup"] = "Démarrer avec Windows",
		["TrayAbout"] = "À propos",
		["TrayQuit"] = "Quitter",
		["BehaviorDescription"] = "Les fenêtres se comportent comme si votre écran ultrawide était composé de plusieurs moniteurs.",
		["StartupDescription"] = "Ultrawide Monitor peut rester discret et démarrer automatiquement avec votre session Windows.",
		["StartupAgentText"] = "L’agent administrateur est installé avec l’installateur et s’exécute uniquement dans votre session. Les fenêtres UAC et le bureau sécurisé restent protégés par Windows.",
		["AppearanceDescription"] = "Choisissez la langue et l’apparence de l’application.",
		["AppearanceLanguageDescription"] = "Choisissez la langue utilisée dans les réglages et la zone de notification.",
		["AppearanceThemeDescription"] = "Utilisez le thème clair, sombre ou celui de Windows.",
		["AppearanceAutoSave"] = "Les changements sont enregistrés automatiquement.",
		["CompatibilityDescription"] = "Ajoutez les applications qui doivent rester en dehors du gestionnaire de zones.",
		["CompatibilityAppsTitle"] = "Applications exclues",
		["CompatibilityAppsDescription"] = "Ces processus ne seront jamais déplacés ou redimensionnés par Ultrawide Monitor.",
		["CompatibilityNoApps"] = "Aucune application exclue.",
		["CompatibilityHint"] = "Saisissez le nom du processus sans l’extension .exe.",
		["ProcessTooltip"] = "Nom du processus sans .exe",
		["StorageText"] = "Les réglages sont conservés localement dans %LocalAppData%\\UltrawideMonitor.",
		["EditorPreset"] = "Disposition",
		["EditorSave"] = "Enregistrer",
		["EditorDelete"] = "Supprimer",
		["EditorApply"] = "Utiliser les zones",
		["EditorPresetName"] = "Nom du preset personnalisé",
		["EditorSplitVertical"] = "Diviser verticalement",
		["EditorSplitHorizontal"] = "Diviser horizontalement",
		["EditorMerge"] = "Fusionner",
		["PresetSaved"] = "Preset enregistré.",
		["EditorDeleted"] = "Preset supprimé.",
		["EditorSaveFailed"] = "Impossible d’enregistrer les modifications.",
		["InvalidLayout"] = "Disposition invalide.",
		["CustomPresetName"] = "Personnalisée"
	};

	private static readonly Dictionary<string, string> En = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
	{
		["Zones"] = "Zones",
		["ZonesDescription"] = "Create custom workspaces for each display.",
		["Behavior"] = "Behavior",
		["Startup"] = "Startup",
		["Appearance"] = "Appearance and language",
		["Compatibility"] = "Compatibility",
		["About"] = "About",
		["Edit"] = "Edit",
		["Apply"] = "Apply",
		["Cancel"] = "Cancel",
		["Reset"] = "Reset",
		["Enabled"] = "Ultrawide Monitor is active",
		["Monitor"] = "Display",
		["Primary"] = "Primary",
		["Preset"] = "Layout",
		["AddPreset"] = "Save as preset",
		["Maximize"] = "Maximize windows into a zone",
		["ShiftBypass"] = "Shift maximizes the whole display",
		["Snap"] = "Snap to edges",
		["SnapDistance"] = "Snap distance",
		["StartWithWindows"] = "Start with Windows",
		["StartMinimized"] = "Start minimized in the notification area",
		["AdminAgent"] = "Administrator agent",
		["Language"] = "Language",
		["Theme"] = "Theme",
		["System"] = "System",
		["Light"] = "Light",
		["Dark"] = "Dark",
		["Add"] = "Add",
		["Remove"] = "Remove",
		["Process"] = "Process",
		["AboutText"] = "Ultrawide Monitor is a Windows 11 zone manager. No account, no telemetry.",
		["GithubCredit"] = "Project, source code and releases: GitHub / ImRedTV",
		["UpdateTitle"] = "Update available",
		["UpdateMessage"] = "Ultrawide Monitor {0} is available. Open the latest GitHub release?",
		["DoubleClick"] = "Double-click the notification icon to edit zones.",
		["NoMonitors"] = "No displays detected.",
		["Selected"] = "Selected",
		["TrayEnabled"] = "Ultrawide Monitor is active",
		["TrayEdit"] = "Edit zones…",
		["TraySettings"] = "Settings…",
		["TrayStartup"] = "Start with Windows",
		["TrayAbout"] = "About",
		["TrayQuit"] = "Quit",
		["BehaviorDescription"] = "Windows behave as if your ultrawide display were several monitors.",
		["StartupDescription"] = "Ultrawide Monitor can stay quiet and start automatically with your Windows session.",
		["StartupAgentText"] = "The administrator agent is installed with setup and runs only in your session. UAC windows and the secure desktop remain protected by Windows.",
		["AppearanceDescription"] = "Choose the application language and appearance.",
		["AppearanceLanguageDescription"] = "Choose the language used in settings and the notification area.",
		["AppearanceThemeDescription"] = "Use the light, dark or Windows theme.",
		["AppearanceAutoSave"] = "Changes are saved automatically.",
		["CompatibilityDescription"] = "Add applications that should remain outside the zone manager.",
		["CompatibilityAppsTitle"] = "Excluded applications",
		["CompatibilityAppsDescription"] = "These processes will never be moved or resized by Ultrawide Monitor.",
		["CompatibilityNoApps"] = "No excluded applications.",
		["CompatibilityHint"] = "Enter the process name without the .exe extension.",
		["ProcessTooltip"] = "Process name without .exe",
		["StorageText"] = "Settings are stored locally in %LocalAppData%\\UltrawideMonitor.",
		["EditorPreset"] = "Layout",
		["EditorSave"] = "Save",
		["EditorDelete"] = "Delete",
		["EditorApply"] = "Use zones",
		["EditorPresetName"] = "Custom preset name",
		["EditorSplitVertical"] = "Split vertically",
		["EditorSplitHorizontal"] = "Split horizontally",
		["EditorMerge"] = "Merge",
		["PresetSaved"] = "Preset saved.",
		["EditorDeleted"] = "Preset deleted.",
		["EditorSaveFailed"] = "Could not save the changes.",
		["InvalidLayout"] = "Invalid layout.",
		["CustomPresetName"] = "Custom"
	};

	public static string Get(string key, string language)
	{
		string value;
		return (language.StartsWith("en", StringComparison.OrdinalIgnoreCase) ? En : Fr).TryGetValue(key, out value) ? value : key;
	}
}

